version: '3.8'

services:
  db:
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - 'mysql_data:/var/lib/mysql'

volumes:
  mysql_data:
