export enum EventType {
  BuildComplete = 'build.complete',
  ReleaseAbandoned = 'ms.vss-release.release-abandoned-event',
  ReleaseCreated = 'ms.vss-release.release-created-event',
  ReleaseDeploymentApprovalCompleted = 'ms.vss-release.deployment-approval-completed-event',
  ReleaseDeploymentApprovalPending = 'ms.vss-release.deployment-approval-pending-event',
  ReleaseDeploymentCompleted = 'ms.vss-release.deployment-completed-event',
  ReleaseDeploymentStarted = 'ms.vss-release.deployment-started-event',
  RunStateChanged = 'ms.vss-pipelines.run-state-changed-event',
  RunStageStateChanged = 'ms.vss-pipelines.stage-state-changed-event',
  RunStageWaitingForApproval = 'ms.vss-pipelinechecks-events.approval-pending',
  CodeCheckedIn = 'tfvc.checkin',
  CodePushed = 'git.push',
  PullRequestCreated = 'git.pullrequest.created',
  PullRequestMergeCommitCreated = 'git.pullrequest.merged',
  PullRequestUpdated = 'git.pullrequest.updated',
  WorkItemCreated = 'workitem.created',
  WorkItemDeleted = 'workitem.deleted',
  WorkItemRestored = 'workitem.restored',
  WorkItemUpdated = 'workitem.updated',
  WorkItemCommented = 'workitem.commented',
}
